### ISSUE TITLE
Store and retrieve the elements from Database instead of list

### ISSUE THREAD

**Issue by codezeeker** [codezeeker/task-mgmt-service#5]
- [x] study database-related item in Python

- [x] use database, and update the code to store and retrieve the items instead of list [I will be updating you the boiler-plate(all necessary settings) for you. you just need to add code to add and retrieve element.]

**Comment by codezeeker** [comment]
@ahamed-sha were you able make any progress?

**Comment by ghost** [comment]
what should I change in the original code?

**Comment by codezeeker** [comment]
it is added in the description above

**Comment by codezeeker** [comment]
use database, and update the code to store and retrieve the items instead of list
